import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner.component.js";
import Card from "../components/card.js";
import CoffeeStore from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      data: CoffeeStore,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  console.log("Home Component");

  const handleOnButtonClick = () => {
    console.log("Hi banner button");
  };
  console.log("props=>", props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={800}
            height={400}
            alt="Hero-image"
          />
        </div>
        {props.data.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.data.map((store) => {
                return (
                  <Card
                    key={store.id}
                    className={styles.card}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
