import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner.component.js";
import Card from "../components/card.js";
//import CoffeeStore from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  const options = {
    method: "GET",
    headers: {
      accept: "application/json",
      Authorization: process.env.FOURSQUARE_API_KEY,
    },
  };

  const response = await fetch(
    "https://api.foursquare.com/v3/places/search?query=coffees&ll=36.7848491374139%2C34.589651058131885&limit=10",
    options
  );
  const data = await response.json();

  return {
    props: {
      data: data.results,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const handleOnButtonClick = () => {
    // console.log("Hi banner button");
  };

  // console.log("props=>", props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" OnClick={handleOnButtonClick} />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={800}
            height={400}
            alt="Hero-image"
          />
        </div>
        {props.data.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.data.map((store) => {
                return (
                  <Card
                    key={store.fsq_id}
                    className={styles.card}
                    name={store.name}
                    imgUrl="https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    href={`/coffee-store/${store.fsq_id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
